title: Clint's Portfolio
email: clint93@uab.edu
description: >- # this means to ignore newlines until "baseurl:"
  Clint's personal blog.

baseurl: ""  # TODO
url: ""
show_excerpts: true
keywords: ["blog", "software", "cars"]

# Build settings
# theme: plainwhite-jekyll
remote_theme: thelehhman/plainwhite-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag # plugin to add metadata tags for search enignes/social networks to better index and display the site

plainwhite:
    name: Clinton Campbell
    tagline: Software Developer & Student
    sitemap: true
    portfolio_image: "assets/avatar.png"
    dark_mode: true
    navigation:
        - title: Projects
          url: "/projects"
        - title: My Resume
          url: "/resume"
        - title: About Me
          url: "/about"
    social_links:
        github: cclint
        #gitlab: clint93
        linkedIn: in/cclint
        twitter: Clinton04424088
    analytics_id: "G-6QC0FGM4W7"
    sitemap: true
    search: true # enables search bar by using the Simple-Jekyll-Search Jekyll plugin. This creates a search.json file containing post meta and contents will be genereated in the root folder. Searches based on user input for posts
    
    

owner:
    name: Clinton Campbell
    job: Software Developer
    bio: TODO
    email: clint93@uab.edu
    github: cclint
    gitlab: clint93

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/